package io.openfednow.shadowledger;

/**
 * Port for real-time card authorization events originating from an upstream card processor.
 *
 * <p>Allows the system to ingest network-level card transactions (e.g., Visa DPS, FIS, Fiserv, Jack Henry)
 * during core banking maintenance windows ("bridge mode"). By consuming these events in real time,
 * the shadow ledger can apply proactive holds and prevent double-spend risks across the FedNow/RTP rails
 * while the primary core is offline.
 *
 * @see ShadowLedger
 */
public interface CardAuthorizationEventListener {

    /**
     * Handles an incoming real-time card debit authorization.
     *
     * <p>Implementations should map the incoming processor event to an atomic debit operation against
     * the shadow ledger (e.g., Redis balance cache) to isolate and hold the authorized funds immediately.
     *
     * @param accountId   the unique internal tracking identifier for the customer account
     * @param amountCents the transaction authorization amount represented in cents
     * @param authCode    the unique approval reference code generated by the card network
     */
    void onAuthorization(String accountId, long amountCents, String authCode);

    /**
     * Handles a card authorization reversal or release event.
     *
     * <p>Reverts a previously registered authorization hold, crediting the corresponding funds
     * back into the shadow ledger balance view.
     *
     * @param accountId        the unique internal tracking identifier for the customer account
     * @param amountCents      the transaction amount to be reversed or released in cents
     * @param originalAuthCode the reference authorization code associated with the initial debit event
     */
    void onReversal(String accountId, long amountCents, String originalAuthCode);
}