package io.openfednow.shadowledger;

import java.math.BigDecimal;

/**
 * Default No-Op implementation of the {@link CardAuthorizationEventListener}.
 *
 * <p>Serves as a passive fallback implementation that performs no operational
 * state changes upon receiving card events. This prevents application context
 * failures when no vendor-specific card processor adapter is explicitly registered.
 */
public class NoOpCardAuthorizationEventListener implements CardAuthorizationEventListener {

    /**
     * Safely ignores an incoming card debit authorization event.
     *
     * @param accountId the unique internal tracking identifier for the customer account
     * @param amount    the transaction authorization amount represented as a {@link BigDecimal}
     * @param authCode  the unique approval reference code generated by the card network
     */
    @Override
    public void onAuthorization(String accountId, BigDecimal amount, String authCode) {
        // No-Op fallback execution path
    }

    /**
     * Safely ignores an incoming card authorization reversal event.
     *
     * @param accountId the unique internal tracking identifier for the customer account
     * @param amount    the transaction amount to be reversed or released as a {@link BigDecimal}
     * @param authCode  the reference authorization code associated with the initial debit event
     */
    @Override
    public void onReversal(String accountId, BigDecimal amount, String authCode) {
        // No-Op fallback execution path
    }
}