package io.openfednow.shadowledger;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Default No-Op implementation of the {@link CardAuthorizationEventListener}.
 *
 * <p>Serves as a passive fallback implementation that logs initialization but performs no
 * operational state changes upon receiving card events. This prevents application context
 * failures when no vendor-specific card processor adapter is explicitly registered.
 */
public class NoOpCardAuthorizationEventListener implements CardAuthorizationEventListener {

    private static final Logger log = LoggerFactory.getLogger(NoOpCardAuthorizationEventListener.class);

    /**
     * Constructs the No-Op listener and logs an informational startup event.
     */
    public NoOpCardAuthorizationEventListener() {
        log.info("Initialized default No-Op CardAuthorizationEventListener.");
    }

    /**
     * Safely ignores an incoming card debit authorization event.
     *
     * @param accountId   the unique internal tracking identifier for the customer account
     * @param amountCents the transaction authorization amount represented in cents
     * @param authCode    the unique approval reference code generated by the card network
     */
    @Override
    public void onAuthorization(String accountId, long amountCents, String authCode) {
        // No-Op fallback execution path
    }

    /**
     * Safely ignores an incoming card authorization reversal event.
     *
     * @param accountId        the unique internal tracking identifier for the customer account
     * @param amountCents      the transaction amount to be reversed or released in cents
     * @param originalAuthCode the reference authorization code associated with the initial debit event
     */
    @Override
    public void onReversal(String accountId, long amountCents, String originalAuthCode) {
        // No-Op fallback execution path
    }
}